name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip hatch hatch-vcs

    - name: Build binary wheel and sdist
      run: hatch build

    - name: Show files
      run: |
        ls dist
