name: Publish to PyPI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip hatch hatch-vcs

    - name: Build binary wheel and sdist
      run: hatch build

    - name: Show files
      run: |
        ls dist

    - name: Publish a Python distribution to PyPI on release
      if: success() && github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
